runmode: debug
general:
    addr: :9090
    dsn: root:123456@(10.211.55.6:3306)/lyanna?charset=utf8&parseTime=True
    redisurl: 10.211.55.6:6379
    sessionsecret: lyanna_blog
    logoutenabled: true



