runmode: debug
general:
    addr: :9080
    dsn: root:123456@(192.168.188.106:3306)/lyanna?charset=utf8&parseTime=True&loc=Local
    sessionsecret: lyanna_blog
    logoutenabled: true
    perpage: 2

github:
    clientid:
    clientsecret:
    authurl:
    # 与github配置的回调地址一致
    redirecturl:
    tokenurl:
